name: JSON functions
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ fromJSON(github) }}     # github 컨텍스트를 JSON 문자열로 변환

